// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using energy_backend.Infrastructure.Data;

#nullable disable

namespace energy_backend.Infrastructure.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    [Migration("20260529115759_updating")]
    partial class updating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("energy_backend.Core.Entities.AggregateDayEnergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AverageActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("AverageCurrentAmps")
                        .HasColumnType("real");

                    b.Property<float>("AveragePowerFactor")
                        .HasColumnType("real");

                    b.Property<float>("AverageVoltageVolts")
                        .HasColumnType("real");

                    b.Property<int>("DataPointsCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EstimatedCost")
                        .HasColumnType("real");

                    b.Property<float>("MaxActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("MinActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalActiveEnergyKwh")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsUnique()
                        .HasFilter("[DeviceId] IS NOT NULL");

                    b.HasIndex("OrgId", "Timestamp");

                    b.ToTable("AggregateDayEnergies");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AggregateHourEnergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AverageActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("AverageCurrentAmps")
                        .HasColumnType("real");

                    b.Property<float>("AveragePowerFactor")
                        .HasColumnType("real");

                    b.Property<float>("AverageVoltageVolts")
                        .HasColumnType("real");

                    b.Property<int>("DataPointsCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EstimatedCost")
                        .HasColumnType("real");

                    b.Property<float>("MaxActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("MinActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalActiveEnergyKwh")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsUnique()
                        .HasFilter("[DeviceId] IS NOT NULL");

                    b.HasIndex("OrgId", "Timestamp");

                    b.ToTable("AggregateHourEnergies");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AggregateMinuteEnergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AverageActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("AverageCurrentAmps")
                        .HasColumnType("real");

                    b.Property<float>("AveragePowerFactor")
                        .HasColumnType("real");

                    b.Property<float>("AverageVoltageVolts")
                        .HasColumnType("real");

                    b.Property<int>("DataPointsCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EstimatedCost")
                        .HasColumnType("real");

                    b.Property<float>("MaxActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("MinActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalActiveEnergyKwh")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsUnique()
                        .HasFilter("[DeviceId] IS NOT NULL");

                    b.HasIndex("OrgId", "Timestamp");

                    b.ToTable("AggregateMinuteEnergies");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AggregateMonthEnergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AverageActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("AverageCurrentAmps")
                        .HasColumnType("real");

                    b.Property<float>("AveragePowerFactor")
                        .HasColumnType("real");

                    b.Property<float>("AverageVoltageVolts")
                        .HasColumnType("real");

                    b.Property<int>("DataPointsCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EstimatedCost")
                        .HasColumnType("real");

                    b.Property<float>("MaxActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("MinActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalActiveEnergyKwh")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsUnique()
                        .HasFilter("[DeviceId] IS NOT NULL");

                    b.HasIndex("OrgId", "Timestamp");

                    b.ToTable("AggregateMonthEnergies");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("EmailCooldownMinutes")
                        .HasColumnType("real");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit");

                    b.Property<float>("InAppCooldownMinutes")
                        .HasColumnType("real");

                    b.Property<bool>("InAppNotificationEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTriggeredEmailAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastTriggeredInAppAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ThresholdValue")
                        .HasColumnType("real");

                    b.HasKey("AlertId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AlertEvent", b =>
                {
                    b.Property<Guid>("AlertEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ThresholdValue")
                        .HasColumnType("real");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("TriggeredValueWatts")
                        .HasColumnType("real");

                    b.HasKey("AlertEventId");

                    b.HasIndex("AlertId");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("RatedPowerWatts")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.EnergyReading", b =>
                {
                    b.Property<Guid>("EnergyReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ActiveEnergyKwh")
                        .HasColumnType("real");

                    b.Property<float>("ActivePowerWatts")
                        .HasColumnType("real");

                    b.Property<float>("CurrentAmps")
                        .HasColumnType("real");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PowerFactor")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("VoltageVolts")
                        .HasColumnType("real");

                    b.HasKey("EnergyReadingId");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsUnique();

                    b.HasIndex("Timestamp", "DeviceId");

                    b.ToTable("EnergyReadings");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Organisation", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EnergyBudgetKwh")
                        .HasColumnType("real");

                    b.Property<float>("EnergyCostPerKwh")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganisationId");

                    b.HasIndex("UserId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Setting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BudgetAlerts")
                        .HasColumnType("bit");

                    b.Property<float>("ElectricityCostPerKwh")
                        .HasColumnType("real");

                    b.Property<Guid>("FavoriteOrg")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PeakAlerts")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("UnusualAlerts")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SettingId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AggregateDayEnergy", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("energy_backend.Core.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AggregateHourEnergy", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("energy_backend.Core.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AggregateMinuteEnergy", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("energy_backend.Core.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AggregateMonthEnergy", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("energy_backend.Core.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Alert", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.AlertEvent", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.Alert", "Alert")
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Device", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.Organisation", "Organisation")
                        .WithMany("Devices")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.EnergyReading", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Organisation", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.User", "User")
                        .WithMany("Organisations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Setting", b =>
                {
                    b.HasOne("energy_backend.Core.Entities.User", "User")
                        .WithOne("Setting")
                        .HasForeignKey("energy_backend.Core.Entities.Setting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.Organisation", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("energy_backend.Core.Entities.User", b =>
                {
                    b.Navigation("Organisations");

                    b.Navigation("Setting");
                });
#pragma warning restore 612, 618
        }
    }
}
